### ISSUE TITLE
Seems transceiver not working. Re-init it.

### ISSUE THREAD

**Issue by metehanemlik** [gsongsong/dw1000-positioning#2]
Example codes are working but when ı am trying to your code, ı am receiving only this. 

Seems transceiver not working. Re-init it.

Thank you for help

**Comment by sjeon87** [comment]
Could you elaborate more?
- What are example codes you mentioned?
- What is your wiring configuration between Raspberry Pi, Arduino and dwm1000?


`Seems transceiver not working. Re-init it.` generally happens when
- Raspberry Pi doesn't send any command to Arduino
- SPI communication between Arduino and dwm1000 fails

**Comment by metehanemlik** [comment]
I did not connect raspberry pi, ı just want to test your code by using a serial port, 

I changed 

volatile char state = STATE_IDLE;  to  volatile char state = STATE_SCAN;

and then it starts to work
